[alexa-top-1m]
name = 'alexa-top-1m'
type = 'csv-zip'
file = '/opt/lists/alexa-top-1m.csv.zip'

[umbrellas-top-1m]
name = 'umbrella-top-1m'
type = 'csv-zip'
file = '/opt/lists/umbrella-top-1m.csv.zip'

[umbrellas-top-1m-tlds]
name = 'umbrella-top-1m-tlds'
type = 'csv-zip'
file = '/opt/lists/umbrella-top-1m-tlds.csv.zip'

